name: Deploy astra-dao -> prod (manual)
on: workflow_dispatch
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2
        with:
          ref: astra-dao

      - name: Install dependencies with yarn
        run: yarn

      - name: Build artifact
        run: yarn build

      - name: Deploy artifact to S3 and invalidate Cloudfront
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: build
          bucket: ${{ secrets.AWS_ASTRA_DAO_PROD_BUCKET }}
          dist-id: ${{ secrets.AWS_ASTRA_DAO_PROD_CLOUDFRONT_DIST_ID }}
          invalidation: / *
